[package]
name = "earth_escape"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.6"
heron = { version = "1.1.0", features = ["2d"] }
wasm-bindgen = "0.2.79"
rand = "0.8.5"